_=[[


TODO

 now --------
- fix zombie pathfind not triggering
- add way to see bricks separately
- delete brick tool
- block break texture
- clear builds button

?? make mobile controls easier? (see babft)


 later ------
- SOLVE FRICKING CYCLIC DEPENDENCIES
- Fix typing in StateMachine
- Adapt StateMachine to a Pip class
- Adapt StateMachine to general pupose and publish to GitHub
- Turn Pip into a fricking package on god atp icl pmo frfr


]]