--[=[
	[INFO]
	author: @halosviel
	created: 2026 May 27
	
	[DESCRIPTION]
	
	[NOTES]
	- 
]=]

-- [REQUIRES]
local class = require("@game/ReplicatedFirst/pip/class")

-- [TYPES]
type self = {
	-- [CONFIG]
	
	-- [ENTRIES]
	
	-- [FUNCTIONS]
	new: ( self: self ) -> nil,
	ready: ( self: self ) -> nil
}
export type Zombie = self

-->

return class {
	new = function(self: self)
		
	end,
	
	ready = function(self: self)
		
	end,
} :: self